/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Archivos.ArchivoVehiculo;
import Controladores.ControladorPersona;
import Controladores.ControladorVehiculo;
import Modelo.Persona;
import Modelo.Vehiculo;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class VehiculoVista extends javax.swing.JInternalFrame {
    public ControladorVehiculo controladorVehiculo;
    public ControladorPersona controladorCliente;
    public DefaultTableModel tblModelVehiculo;
    public DefaultListModel lstModelCliente;
    public ArchivoVehiculo archivoVehiculo;
    /**
     * Creates new form VehiculoVista
     */
    public VehiculoVista(ControladorVehiculo controladorVehiculo,ControladorPersona controladorCliente, ArchivoVehiculo archivoVehiculo) {
        initComponents();
        this.controladorCliente=controladorCliente;
        this.controladorVehiculo=controladorVehiculo;
        this.archivoVehiculo=archivoVehiculo;
        controladorVehiculo.setListaVehiculos(archivoVehiculo.leer());
        this.tblModelVehiculo=(DefaultTableModel) jtDatos.getModel();
        this.lstModelCliente=new DefaultListModel();
        jlPropietarios.setModel(lstModelCliente);
        jtDatos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent v) {
                if (jtDatos.getSelectedRow()>=0) {
                    controladorVehiculo.setVehiculo(controladorVehiculo.getListaVehiculos().get(jtDatos.getSelectedRow()));
                    cargarValores();
                }else{
                    limpiarDatos();
                }
            }
        });
        cargarDatos();
        filtrarClientes();
    }
    public void cargarValores(){
        txtMarca.setText(controladorVehiculo.getVehiculo().getMarca());
        txtModelo.setText(controladorVehiculo.getVehiculo().getModelo());
        txtPlaca.setText(controladorVehiculo.getVehiculo().getPlaca());
        txtPropietario.setText(controladorVehiculo.getVehiculo().getCliente().getCedula());
    }
    public void cargarDatos(){
        tblModelVehiculo.setRowCount(0);
        for (Vehiculo vehiculo : controladorVehiculo.getListaVehiculos()) {
            String datos[]={String.valueOf(vehiculo.getId()),vehiculo.getPlaca(),vehiculo.getMarca()
                ,vehiculo.getModelo(),vehiculo.getCliente().getCedula()
            };
            tblModelVehiculo.addRow(datos);
        }
    }
    public void filtrarClientes(){
        lstModelCliente.removeAllElements();
        for (Persona dato : controladorCliente.getDatos()) {
            if (dato.getCedula().contains(txtPropietario.getText())) {
                lstModelCliente.addElement(dato.getCedula());
            }
        }
    }
    public void limpiarDatos(){
        txtMarca.setText("");
        txtModelo.setText("");
        txtPlaca.setText("");
        txtPropietario.setText("");
        filtrarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlPropietarios = new javax.swing.JList<>();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vehiculos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                GuardarVehiculos(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        jLabel3.setText("Placa");

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Placa", "Marca", "Modelo", "Propietario"
            }
        ));
        jScrollPane1.setViewportView(jtDatos);
        if (jtDatos.getColumnModel().getColumnCount() > 0) {
            jtDatos.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel4.setText("Propietario");

        txtPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropietarioActionPerformed(evt);
            }
        });
        txtPropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPropietarioKeyPressed(evt);
            }
        });

        jScrollPane2.setViewportView(jlPropietarios);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtModelo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrear)
                            .addComponent(btnEliminar))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCrear))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnEliminar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        controladorVehiculo.eliminar(txtPlaca.getText());
        cargarDatos();
        limpiarDatos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        Persona cliente;
        if (jlPropietarios.getSelectedValue()!=null) {
            cliente=controladorCliente.buscar(jlPropietarios.getSelectedValue());
        }else{
            cliente=controladorCliente.buscar(txtPropietario.getText());
        }
        if (controladorVehiculo.getVehiculo()!=null) {
            controladorVehiculo.actualizar(txtPlaca.getText(), txtMarca.getText(), txtModelo.getText(),cliente);
        }else{
            controladorVehiculo.crear(txtPlaca.getText(), txtMarca.getText(), txtModelo.getText(),cliente);
        }
        cargarDatos();
        limpiarDatos();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropietarioActionPerformed
        // TODO add your handling code here:
        filtrarClientes();
    }//GEN-LAST:event_txtPropietarioActionPerformed

    private void txtPropietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPropietarioKeyPressed
        // TODO add your handling code here:
        filtrarClientes();
    }//GEN-LAST:event_txtPropietarioKeyPressed

    private void GuardarVehiculos(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_GuardarVehiculos
        // TODO add your handling code here:
        archivoVehiculo.escribir(controladorVehiculo.getListaVehiculos());
    }//GEN-LAST:event_GuardarVehiculos


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JList<String> jlPropietarios;
    private javax.swing.JTable jtDatos;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropietario;
    // End of variables declaration//GEN-END:variables
}
