/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import controlador.ControladorEmpresa;
import controlador.ControladorPersona;
import modelo.Cliente;
import modelo.Directivo;
import modelo.Empleado;

/**
 *
 * @author Cristian
 */
public class Principal extends javax.swing.JFrame {

   public ControladorEmpresa controladorEmpresa = new ControladorEmpresa();
    public ControladorPersona controladorPersona = new ControladorPersona();
    public EmpresaVista empresaVista;
    public VistaPersona vistaPersona;
    public Principal() {
        initComponents();
        controladorEmpresa = new ControladorEmpresa();
        controladorPersona = new ControladorPersona();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mniEmpresa = new javax.swing.JMenu();
        mniGestion = new javax.swing.JMenuItem();
        mniPersonal = new javax.swing.JMenu();
        mniClientes = new javax.swing.JMenuItem();
        mniDirectivo = new javax.swing.JMenuItem();
        mniEmpleados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("ProgresarEC"); // NOI18N

        javax.swing.GroupLayout dtpPrincipalLayout = new javax.swing.GroupLayout(dtpPrincipal);
        dtpPrincipal.setLayout(dtpPrincipalLayout);
        dtpPrincipalLayout.setHorizontalGroup(
            dtpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        dtpPrincipalLayout.setVerticalGroup(
            dtpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        mniEmpresa.setText("Empresa");

        mniGestion.setText("Gestion");
        mniGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGestionActionPerformed(evt);
            }
        });
        mniEmpresa.add(mniGestion);

        jMenuBar1.add(mniEmpresa);

        mniPersonal.setText("Personal");

        mniClientes.setText("Clientes");
        mniClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClientesActionPerformed(evt);
            }
        });
        mniPersonal.add(mniClientes);

        mniDirectivo.setText("Directivos");
        mniDirectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDirectivoActionPerformed(evt);
            }
        });
        mniPersonal.add(mniDirectivo);

        mniEmpleados.setText("Empleados");
        mniEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpleadosActionPerformed(evt);
            }
        });
        mniPersonal.add(mniEmpleados);

        jMenuBar1.add(mniPersonal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClientesActionPerformed
        // TODO add your handling code here:
        vistaPersona = new VistaPersona(controladorEmpresa, controladorPersona, Cliente.class);
        dtpPrincipal.add(vistaPersona);
        vistaPersona.show();
    }//GEN-LAST:event_mniClientesActionPerformed

    private void mniGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGestionActionPerformed
        // TODO add your handling code here:
        empresaVista = new EmpresaVista(controladorEmpresa);
        dtpPrincipal.add(empresaVista);
        empresaVista.show();
    }//GEN-LAST:event_mniGestionActionPerformed

    private void mniDirectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDirectivoActionPerformed
        // TODO add your handling code here:
        vistaPersona = new VistaPersona(controladorEmpresa, controladorPersona, Directivo.class);
        dtpPrincipal.add(vistaPersona);
        vistaPersona.show();
    }//GEN-LAST:event_mniDirectivoActionPerformed

    private void mniEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpleadosActionPerformed
        // TODO add your handling code here:
        vistaPersona = new VistaPersona(controladorEmpresa, controladorPersona, Empleado.class);
        dtpPrincipal.add(vistaPersona);
        vistaPersona.show();
    }//GEN-LAST:event_mniEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtpPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniClientes;
    private javax.swing.JMenuItem mniDirectivo;
    private javax.swing.JMenuItem mniEmpleados;
    private javax.swing.JMenu mniEmpresa;
    private javax.swing.JMenuItem mniGestion;
    private javax.swing.JMenu mniPersonal;
    // End of variables declaration//GEN-END:variables
}
